# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- staging

resources:
- repo: self

pool:
  vmImage: ubuntu-latest

variables:
  containerRegistry: docker-registry
  azureSubscription: azure-service-connection

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistry)
        repository: minhledang/asset-management-fe-staging
        command: build
        Dockerfile: Dockerfile
        tags: latest
        arguments: --build-arg API_URL=$(API_URL_STAGING) --build-arg NEXT_PUBLIC_APP_URL=$(NEXT_PUBLIC_APP_URL_STAGING)
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistry)
        repository: minhledang/asset-management-fe-staging
        command: push
        tags: latest

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
      - task: AzureWebAppContainer@1
        inputs:
          azureSubscription: $(azureSubscription)
          appName: asset-management-fe-staging
          containers: minhledang/asset-management-fe-staging:latest
